include:
  - project: 'IaC/ci-templates'
    ref: main
    file: '/ci-templates/templates.yaml'
  - project: 'IaC/ci-templates'
    ref: main
    file: '/ci-templates/sre-templates.yaml'

stages:
  - build
  - publish
  - deploy


build:
  stage: build
  image: golang:1.19
  script:
    - make ci-build
    - cp docker/prod/Dockerfile ./
  artifacts:
    # instead of manually adding i.e. the built binaries, we can instead just
    # grab anything not tracked in Git
    untracked: true
    expire_in: 1 hour

publish:
  stage: publish
  extends: .build_docker_image_kaniko
  variables:
    IMAGE_TAG: ${CI_PIPELINE_IID}
    CI_PROJECT_PATH_SLUG: ${CI_PROJECT_NAME}
  except:
    - tags
  only:
    - branches

# deploy test-tooling:
#   extends: .deploy-sre-test-tooling
#   when: manual
#   except:
#     - tags
#   dependencies:
#     - publish
#   variables:
#     VALUES: '
#       spec.source.helm.valuesObject.sreSlith.tag: "${CI_PIPELINE_IID}"
#       '

# deploy tooling:
#   extends: .deploy-sre-tooling
#   when: manual
#   except:
#     - tags
#   dependencies:
#     - publish
#   variables:
#     VALUES: '
#       spec.source.helm.valuesObject.sreSlith.tag: "${CI_PIPELINE_IID}"
#       '